### PR TITLE
Allow image uploads

### PR DESCRIPTION
**Pull request by seppo0010**
Creates a new dialog where you can drag and drop an image and it helps you get started. See screenshot attached for the dialog and an example of what Homer Simpson looks like.

screenshot 2015-01-04 at 18 03 41

### CODE REVIEW

**Comment by jennschiffer** [comment]
fyi i didn't forget about this - testing it later today!

**Comment by seppo0010** [comment]
:smile:

**Comment by seppo0010** [comment]
Feel free to make suggestions about the interface, ux, etc.

**Comment by seppo0010** [comment]
:(

**Comment by jennschiffer** [comment]
Hey! I'm sorry I've been busy and traveling!

**Comment by jennschiffer** [comment]
I need to rework some UI stuff but then will get back to this PR.

**Pull request closed without merging**
