### PR TITLE
Treat digitizer pen eraser as transparent when drawing

### PR DESCRIPTION
**Pull request by jstarks**
This adds pointer event support and uses it to detect the eraser on my Surface Book's pen. When the eraser is used, it behaves the same as the pen tip but always uses the transparent color.

I'm not a JavaScript programmer, please be gentle!

### CODE REVIEW

**Comment by jennschiffer** [comment]
hey - just wanted you to know that i have time this week to work on this and i'm waiting on a friend with a surface to test this out - thanks for your patience! :santa:

**Comment by nicksahler** [comment]
This is so cool! I have a Surface Book too!

**Comment by jstarks** [comment]
:(

**Comment by jennschiffer** [comment]
just closing it for now until i can access a device to test - it will need reworking to avoid merge conflicts anyway. don't worry - closing doesn't make it go away forever!

**Comment by jstarks** [comment]
Haha, that's OK, not a problem. Probably there's a better way to make the change by now, anyway.

**Pull request closed without merging**
